config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :disasters do
    resources :comments, :controller => "disaster_comments"
  end

  root :to => "disasters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :disasters
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :description
  belongs_to :disaster
end

app/models/disaster.rb
class Disaster < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, :dependent => :destroy
  validates_presence_of :title, :content

  delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :disasters , :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/disaster_comments_controller.rb
class DisasterCommentsController < ApplicationController
  before_action :find_disaster
  before_action :find_own_commment, :only => [:edit, :update, :destroy]
  # 未排版
  def index
    @comments = @disaster.comments
  end

  def show
    @comment = @disaster.comments.find(params[:id])
  end

  def new
    @comment = @disaster.comments.build
  end

  def create
    @comment = @disaster.comments.build(attendee_params)
    if @comment.save
      flash[:notice] = "新增成功"
      redirect_to disaster_path(@disaster)
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @comment.update(attendee_params)
      flash[:notice] = "修改成功"
      redirect_to disaster_path(@disaster)
    else
      render :action => :edit
    end

  end

  def destroy
    @comment.destroy
    flash[:notice] = "刪除成功"
    redirect_to disaster_comments_url(@disaster)
  end

  protected

  def find_disaster
    @disaster = Disaster.find(params[:disaster_id])
  end

  def attendee_params
    params.require(:comment).permit(:description)
  end

  def find_own_commment
    @comment = current_user.comments.find(params[:id])
  end
end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_disaster, :only => [:show]
  before_action :set_own_disaster, :only => [:edit, :update, :destroy]
  # 本來的程式碼在刪除修改的時候並未對使用者進行驗證
  def index
    @disasters = Disaster.page(params[:page]).per(5)
  end

  def new
    @disaster = Disaster.new
  end

  def create
    @disaster = Disaster.new(disaster_params)
    @disaster.user = current_user
    if @disaster.save
      redirect_to disasters_path
      flash[:notice] = "disaster event was successfully created"
    else
      render :action => :new
    end
  end

  def show
    @comments = @disaster.comments
  end

  def edit
  end

  def update
    if @disaster.update(disaster_params)
      redirect_to disaster_path(@disaster)
      flash[:notice] = "disaster event was successfully updated"
    else
      render :action => :edit
    end
  end

  def destroy
    @disaster.destroy
    redirect_to :action => :index
    flash[:alert] = "disaster event was successfully deleted"
  end

  private

  def disaster_params
    params.require(:disaster).permit(:title, :content, :category_id, :user_id)
  end

  def set_disaster
    @disaster = Disaster.find(params[:id])
  end

  def set_own_disaster
    @disaster = current_user.disasters.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disaster_comments_helper.rb
module DisasterCommentsHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/views/disaster_comments/edit.html.erb
<%= form_for @comment, :url => disaster_comment_path(@disaster, @comment), :html => { :method => :patch } do |f| %>
    <% if @comment.errors.any? %>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
   <%= f.text_field :description %>
   <%= f.submit %>
<% end %>

<%= link_to "Back to Last Page", disaster_path(@disaster), :class => 'btn btn-info' %>

app/views/disaster_comments/new.html.erb
<%= form_for @comment, :url => disaster_comments_path(@disaster) do |f| %>
    <% if @comment.errors.any? %>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.text_field :description %>
    <%= f.submit %>
<% end %>
<%= link_to "Back to Last Page", disaster_path(@disaster) %>

app/views/disasters/_form.html.erb
<% if @disaster.errors.any? %>
    <ul>
      <% @disaster.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= f.label :title, "Title" %>
<%= f.text_field :title %>

<%= f.label :content, "content" %>
<%= f.text_area :content %>

<div class="form-group">
  <%= f.label :category_id, "Category_id" %>
  <% Category.all.each do |c| %>
      <%= f.radio_button :category_id, c.id %> <%= c.name %>
  <% end %>
</div>

app/views/disasters/edit.html.erb
<%= form_for @disaster, :url => disaster_path(@disaster), :method => :patch do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "update"%>
<% end %>
<%= link_to "Back to Last Page", disasters_path, :class => 'btn btn-info'  %>

app/views/disasters/index.html.erb
<h1>地震災情支援網</h1>

<table class = "table">
  <tr>
    <td>
      <h3>Category</h3>
    </td>
    <td>
      <h3>Title</h3>
    </td>
    <td>
      <h3>Created_at</h3>
    </td>
    <td>
      <h3>Edit/Delete</h3>
    </td>
  </tr>
  <tr>
  <% @disasters.each do |disaster|%>
    <td>
      <%= disaster.category.name%>
    </td>
    <td>
      <%= link_to "#{disaster.title}", disaster_path(disaster) %>
    </td>
    <td>
      <%= disaster.created_at %>
    </td>
    <td>
       <%= link_to "Edit", edit_disaster_path(disaster) , :class => "btn btn-default"%>
       <%= link_to "Delete", disaster_path(disaster), :method => :delete , :class => "btn btn-danger", :data => { :confirm => "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to "New Disaster Event", new_disaster_path,:class => 'btn btn-primary' %>


<%= paginate @disasters %>

app/views/disasters/new.html.erb
<%= form_for @disaster , :url => disasters_path do |f|%>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create Event"%>
<% end %>

app/views/disasters/show.html.erb
<h3>Disaster Info</h3>
<h4>[Category:] <%= @disaster.category_name %></h4>
  <h4>Title</h4>
<%= @disaster.title %>
  <h4>Content</h4>
<%= simple_format(@disaster.content) %>

<%= link_to 'Add new comment', new_disaster_comment_path(@disaster), :class => 'btn btn-primary'  %>
<%= link_to "Back to Index", disasters_path, :class => 'btn btn-success' %>

<h3>comments</h3>

<table class ='table'>
<% @comments.each do |comment| %>
  <tr>
    <td width = 50%>
      <%= comment.description %>
    </td>
    <td>
      <%= link_to 'edit', edit_disaster_comment_path(@disaster, comment), :class => 'btn btn-info' %>
      <%= link_to 'destroy', disaster_comment_path(@disaster, comment),
                              :method => :delete, :class => 'btn btn-danger' %>
    </td>
  </tr>  
<% end %>
</table>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>
  
  <p style="color: green"><%= flash[:notice] %></p>
  <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>